---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  rubocop:
    enabled: true
  eslint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.rb"
exclude_paths: []
